version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  build:
    desc: Build the CLI tool
    cmds:
      - go build -o cookhub ./cmd/cookhub
    deps: [templ]

  install:
    desc: Install the CLI tool
    cmds:
      - go install ./cmd/cookhub
    deps: [templ]

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  templ:
    desc: Build templates
    cmds:
      - templ generate
    sources:
      - ./**/*.templ
    generates:
      - ./**/*_templ.go

  lint:
    desc: Run all linters
    cmds:
      - go vet ./...

  format:
    desc: Run all formatters
    cmds:
      - go fmt ./...
