// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestionRun = `-- name: CreateIngestionRun :one
insert into ingestion_runs (repository_id, branch, commit_sha) values (
    $1, $2, $3
) returning id
`

type CreateIngestionRunParams struct {
	RepositoryID string
	Branch       string
	CommitSha    string
}

func (q *Queries) CreateIngestionRun(ctx context.Context, arg CreateIngestionRunParams) (string, error) {
	row := q.db.QueryRow(ctx, createIngestionRun, arg.RepositoryID, arg.Branch, arg.CommitSha)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getCommitShaByRepo = `-- name: GetCommitShaByRepo :one
with latest_run as (
    select
        ir.commit_sha,
        row_number() over (
            order by ir.started_at desc
        ) as rn
    from ingestion_runs ir
    join repositories r on ir.repository_id = r.id
    where r.id = $1
)

select commit_sha from latest_run
where rn = 1
`

func (q *Queries) GetCommitShaByRepo(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCommitShaByRepo, id)
	var commit_sha string
	err := row.Scan(&commit_sha)
	return commit_sha, err
}

const getFile = `-- name: GetFile :one
with latest_run as (
    select
        ir.id, ir.repository_id, ir.branch, ir.commit_sha, ir.status, ir.started_at, ir.files_processed_count, ir.completed_at, ir.error_message,
        row_number() over (
            order by ir.started_at desc
        ) as rn
    from ingestion_runs ir
    join repositories r on ir.repository_id = r.id
    where
        r.provider = $1
        and r.owner = $2
        and r.repo_name = $3
)

select f.id, f.ingestion_run_id, f.created_at, f.path, f.basename, f.stem, f.extension, f.content, f.size_bytes, f.hash
from files f
join latest_run lr on f.ingestion_run_id = lr.id
where
    lr.rn = 1
    and f.path = $4
`

type GetFileParams struct {
	Provider string
	Owner    string
	RepoName string
	Path     string
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile,
		arg.Provider,
		arg.Owner,
		arg.RepoName,
		arg.Path,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.IngestionRunID,
		&i.CreatedAt,
		&i.Path,
		&i.Basename,
		&i.Stem,
		&i.Extension,
		&i.Content,
		&i.SizeBytes,
		&i.Hash,
	)
	return i, err
}

const getFiles = `-- name: GetFiles :many
with latest_run as (
    select
        r.provider,
        r.owner,
        r.repo_name,
        ir.id, ir.repository_id, ir.branch, ir.commit_sha, ir.status, ir.started_at, ir.files_processed_count, ir.completed_at, ir.error_message,
        row_number() over (
            order by ir.started_at desc
        ) as rn
    from ingestion_runs ir
    join repositories r on ir.repository_id = r.id
    where
        r.provider = $1
        and r.owner = $2
        and r.repo_name = $3
)

select
    lr.provider,
    lr.owner,
    lr.repo_name,
    f.id, f.ingestion_run_id, f.created_at, f.path, f.basename, f.stem, f.extension, f.content, f.size_bytes, f.hash
from files f
join latest_run lr on f.ingestion_run_id = lr.id
where lr.rn = 1
`

type GetFilesParams struct {
	Provider string
	Owner    string
	RepoName string
}

type GetFilesRow struct {
	Provider       string
	Owner          string
	RepoName       string
	ID             string
	IngestionRunID string
	CreatedAt      pgtype.Timestamptz
	Path           string
	Basename       string
	Stem           string
	Extension      string
	Content        string
	SizeBytes      int32
	Hash           []byte
}

func (q *Queries) GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error) {
	rows, err := q.db.Query(ctx, getFiles, arg.Provider, arg.Owner, arg.RepoName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesRow
	for rows.Next() {
		var i GetFilesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Owner,
			&i.RepoName,
			&i.ID,
			&i.IngestionRunID,
			&i.CreatedAt,
			&i.Path,
			&i.Basename,
			&i.Stem,
			&i.Extension,
			&i.Content,
			&i.SizeBytes,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type ImportFilesParams struct {
	IngestionRunID string
	Path           string
	Basename       string
	Stem           string
	Extension      string
	Content        string
	SizeBytes      int32
	Hash           []byte
}

const listIngestionRuns = `-- name: ListIngestionRuns :many
select id, repository_id, branch, commit_sha, status, started_at, files_processed_count, completed_at, error_message from ingestion_runs
`

func (q *Queries) ListIngestionRuns(ctx context.Context) ([]IngestionRun, error) {
	rows, err := q.db.Query(ctx, listIngestionRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestionRun
	for rows.Next() {
		var i IngestionRun
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.StartedAt,
			&i.FilesProcessedCount,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
select id, url, provider, owner, repo_name, branch from repositories
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Provider,
			&i.Owner,
			&i.RepoName,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunAsCompleted = `-- name: MarkRunAsCompleted :exec
update ingestion_runs set
    status = 'completed', files_processed_count = $1, completed_at = now()
where id = $2
`

type MarkRunAsCompletedParams struct {
	FilesProcessedCount pgtype.Int4
	ID                  string
}

func (q *Queries) MarkRunAsCompleted(ctx context.Context, arg MarkRunAsCompletedParams) error {
	_, err := q.db.Exec(ctx, markRunAsCompleted, arg.FilesProcessedCount, arg.ID)
	return err
}

const markRunAsFailed = `-- name: MarkRunAsFailed :exec
update ingestion_runs set
    status = 'failed',
    files_processed_count = $1,
    completed_at = now(),
    error_message = $2
where id = $3
`

type MarkRunAsFailedParams struct {
	FilesProcessedCount pgtype.Int4
	ErrorMessage        pgtype.Text
	ID                  string
}

func (q *Queries) MarkRunAsFailed(ctx context.Context, arg MarkRunAsFailedParams) error {
	_, err := q.db.Exec(ctx, markRunAsFailed, arg.FilesProcessedCount, arg.ErrorMessage, arg.ID)
	return err
}
