// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateFile implements pgx.CopyFromSource.
type iteratorForCreateFile struct {
	rows                 []CreateFileParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateFile) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateFile) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JobID,
		r.rows[0].Name,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForCreateFile) Err() error {
	return nil
}

func (q *Queries) CreateFile(ctx context.Context, arg []CreateFileParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"files"}, []string{"job_id", "name", "content"}, &iteratorForCreateFile{rows: arg})
}
