// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForImportFiles implements pgx.CopyFromSource.
type iteratorForImportFiles struct {
	rows                 []ImportFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].IngestionRunID,
		r.rows[0].Path,
		r.rows[0].Basename,
		r.rows[0].Stem,
		r.rows[0].Extension,
		r.rows[0].Content,
		r.rows[0].SizeBytes,
		r.rows[0].Hash,
	}, nil
}

func (r iteratorForImportFiles) Err() error {
	return nil
}

func (q *Queries) ImportFiles(ctx context.Context, arg []ImportFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"files"}, []string{"ingestion_run_id", "path", "basename", "stem", "extension", "content", "size_bytes", "hash"}, &iteratorForImportFiles{rows: arg})
}
