// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (job_id, name, content) VALUES ($1, $2, $3)
`

type CreateFileParams struct {
	JobID   string
	Name    string
	Content string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile, arg.JobID, arg.Name, arg.Content)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (slug, commit_sha) VALUES ($1, $2) RETURNING id
`

type CreateJobParams struct {
	Slug      string
	CommitSha string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (string, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Slug, arg.CommitSha)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getFileByName = `-- name: GetFileByName :one
SELECT
    created_at,
    name,
    content
FROM files
WHERE job_id = $1 AND name = $2
`

type GetFileByNameParams struct {
	JobID string
	Name  string
}

type GetFileByNameRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
}

func (q *Queries) GetFileByName(ctx context.Context, arg GetFileByNameParams) (GetFileByNameRow, error) {
	row := q.db.QueryRow(ctx, getFileByName, arg.JobID, arg.Name)
	var i GetFileByNameRow
	err := row.Scan(&i.CreatedAt, &i.Name, &i.Content)
	return i, err
}

const getFilesByJob = `-- name: GetFilesByJob :many
SELECT
    created_at,
    name,
    content
FROM files
WHERE job_id = $1
`

type GetFilesByJobRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
}

func (q *Queries) GetFilesByJob(ctx context.Context, jobID string) ([]GetFilesByJobRow, error) {
	rows, err := q.db.Query(ctx, getFilesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByJobRow
	for rows.Next() {
		var i GetFilesByJobRow
		if err := rows.Scan(&i.CreatedAt, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobs = `-- name: GetJobs :many
SELECT id, created_at, slug, commit_sha FROM jobs
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Slug,
			&i.CommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestJobBySlug = `-- name: GetLatestJobBySlug :one
SELECT id FROM jobs
WHERE slug = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestJobBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestJobBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRecipes = `-- name: GetRecipes :many
SELECT
    f.created_at,
    f.name,
    f.content,
    j.slug,
    j.commit_sha
FROM files AS f
INNER JOIN jobs AS j ON f.job_id = j.id
`

type GetRecipesRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
	Slug      string
	CommitSha string
}

func (q *Queries) GetRecipes(ctx context.Context) ([]GetRecipesRow, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesRow
	for rows.Next() {
		var i GetRecipesRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Name,
			&i.Content,
			&i.Slug,
			&i.CommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
