// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRepositoryMetadata = `-- name: AddRepositoryMetadata :exec
INSERT INTO repo_metadata (job_id, provider, owner, name, response) VALUES (
    $1, $2, $3, $4, $5
)
`

type AddRepositoryMetadataParams struct {
	JobID    string
	Provider string
	Owner    string
	Name     string
	Response []byte
}

func (q *Queries) AddRepositoryMetadata(ctx context.Context, arg AddRepositoryMetadataParams) error {
	_, err := q.db.Exec(ctx, addRepositoryMetadata,
		arg.JobID,
		arg.Provider,
		arg.Owner,
		arg.Name,
		arg.Response,
	)
	return err
}

type CreateFileParams struct {
	JobID   string
	Name    string
	Content string
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (slug, commit_sha) VALUES ($1, $2) RETURNING id
`

type CreateJobParams struct {
	Slug      string
	CommitSha string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (string, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Slug, arg.CommitSha)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAllFiles = `-- name: GetAllFiles :many
SELECT id, created_at, job_id, name, content FROM files
`

func (q *Queries) GetAllFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getAllFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.JobID,
			&i.Name,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRepos = `-- name: GetAllRepos :many
SELECT DISTINCT ON (provider, owner, name)
    provider,
    owner,
    name
FROM repo_metadata
ORDER BY provider, owner, name, created_at DESC
`

type GetAllReposRow struct {
	Provider string
	Owner    string
	Name     string
}

func (q *Queries) GetAllRepos(ctx context.Context) ([]GetAllReposRow, error) {
	rows, err := q.db.Query(ctx, getAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReposRow
	for rows.Next() {
		var i GetAllReposRow
		if err := rows.Scan(&i.Provider, &i.Owner, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByName = `-- name: GetFileByName :one
SELECT
    created_at,
    name,
    content
FROM files
WHERE job_id = $1 AND name = $2
`

type GetFileByNameParams struct {
	JobID string
	Name  string
}

type GetFileByNameRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
}

func (q *Queries) GetFileByName(ctx context.Context, arg GetFileByNameParams) (GetFileByNameRow, error) {
	row := q.db.QueryRow(ctx, getFileByName, arg.JobID, arg.Name)
	var i GetFileByNameRow
	err := row.Scan(&i.CreatedAt, &i.Name, &i.Content)
	return i, err
}

const getFilesByJob = `-- name: GetFilesByJob :many
SELECT
    created_at,
    name,
    content
FROM files
WHERE job_id = $1
`

type GetFilesByJobRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
}

func (q *Queries) GetFilesByJob(ctx context.Context, jobID string) ([]GetFilesByJobRow, error) {
	rows, err := q.db.Query(ctx, getFilesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByJobRow
	for rows.Next() {
		var i GetFilesByJobRow
		if err := rows.Scan(&i.CreatedAt, &i.Name, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByRepo = `-- name: GetFilesByRepo :many
SELECT
    f.id,
    f.name,
    f.content,
    f.created_at,
    j.slug,
    j.commit_sha,
    j.status,
    rm.provider,
    rm.owner,
    rm.name AS repo_name
FROM files f
JOIN jobs j ON f.job_id = j.id
JOIN repo_metadata rm ON j.id = rm.job_id
WHERE
    j.id = (
        SELECT job_id
        FROM repo_metadata m
        WHERE m.provider = $1 AND m.owner = $2 AND m.name = $3
        ORDER BY m.created_at DESC
        LIMIT 1
    )
ORDER BY f.name
`

type GetFilesByRepoParams struct {
	Provider string
	Owner    string
	Name     string
}

type GetFilesByRepoRow struct {
	ID        string
	Name      string
	Content   string
	CreatedAt pgtype.Timestamptz
	Slug      string
	CommitSha string
	Status    StatusEnum
	Provider  string
	Owner     string
	RepoName  string
}

func (q *Queries) GetFilesByRepo(ctx context.Context, arg GetFilesByRepoParams) ([]GetFilesByRepoRow, error) {
	rows, err := q.db.Query(ctx, getFilesByRepo, arg.Provider, arg.Owner, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByRepoRow
	for rows.Next() {
		var i GetFilesByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.Slug,
			&i.CommitSha,
			&i.Status,
			&i.Provider,
			&i.Owner,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobs = `-- name: GetJobs :many
SELECT id, created_at, slug, commit_sha, status FROM jobs
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Slug,
			&i.CommitSha,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestJobBySlug = `-- name: GetLatestJobBySlug :one
SELECT id FROM jobs
WHERE slug = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestJobBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestJobBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRecipePageData = `-- name: GetRecipePageData :one
SELECT
    f.content,
    rm.response
FROM files f
INNER JOIN
    repo_metadata rm
    ON f.job_id = rm.job_id AND f.job_id = $1 AND f.name = $2
`

type GetRecipePageDataParams struct {
	JobID string
	Name  string
}

type GetRecipePageDataRow struct {
	Content  string
	Response []byte
}

func (q *Queries) GetRecipePageData(ctx context.Context, arg GetRecipePageDataParams) (GetRecipePageDataRow, error) {
	row := q.db.QueryRow(ctx, getRecipePageData, arg.JobID, arg.Name)
	var i GetRecipePageDataRow
	err := row.Scan(&i.Content, &i.Response)
	return i, err
}

const getRecipes = `-- name: GetRecipes :many
SELECT
    f.created_at,
    f.name,
    f.content,
    j.slug,
    j.commit_sha
FROM files AS f
INNER JOIN jobs AS j ON f.job_id = j.id
`

type GetRecipesRow struct {
	CreatedAt pgtype.Timestamptz
	Name      string
	Content   string
	Slug      string
	CommitSha string
}

func (q *Queries) GetRecipes(ctx context.Context) ([]GetRecipesRow, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesRow
	for rows.Next() {
		var i GetRecipesRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Name,
			&i.Content,
			&i.Slug,
			&i.CommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepoMetadataByJob = `-- name: GetRepoMetadataByJob :one
SELECT id, created_at, job_id, provider, owner, name, response FROM repo_metadata
WHERE job_id = $1
`

func (q *Queries) GetRepoMetadataByJob(ctx context.Context, jobID string) (RepoMetadatum, error) {
	row := q.db.QueryRow(ctx, getRepoMetadataByJob, jobID)
	var i RepoMetadatum
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.JobID,
		&i.Provider,
		&i.Owner,
		&i.Name,
		&i.Response,
	)
	return i, err
}

const setJobStatus = `-- name: SetJobStatus :exec
UPDATE jobs SET status = $1
WHERE id = $2
`

type SetJobStatusParams struct {
	Status StatusEnum
	ID     string
}

func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) error {
	_, err := q.db.Exec(ctx, setJobStatus, arg.Status, arg.ID)
	return err
}
