// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	JobID     string
	Name      string
	Content   string
}

type Job struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	Slug      string
	CommitSha string
}
