// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Status string

const (
	StatusProcessing Status = "processing"
	StatusCompleted  Status = "completed"
	StatusFailed     Status = "failed"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type File struct {
	ID             string
	IngestionRunID string
	CreatedAt      pgtype.Timestamptz
	Path           string
	Basename       string
	Stem           string
	Extension      string
	Content        string
	SizeBytes      int32
	Hash           []byte
}

type IngestionRun struct {
	ID                  string
	RepositoryID        string
	Branch              string
	CommitSha           string
	Status              Status
	StartedAt           pgtype.Timestamptz
	FilesProcessedCount pgtype.Int4
	CompletedAt         pgtype.Timestamptz
	ErrorMessage        pgtype.Text
}

type Repository struct {
	ID       string
	Url      string
	Provider string
	Owner    string
	RepoName string
	Branch   string
}
